RAW_DIR = "data/raw/"
PROCESSED_DIR = "data/processed/"

AFFNIST_RAW_DIR = RAW_DIR + "affnist/"

FOREST_FIRES_FILENAME = "forestfires.csv"
FOREST_FIRES_DIR = "forest+fires/"
FOREST_FIRES_RAW_FILE = RAW_DIR + FOREST_FIRES_DIR + FOREST_FIRES_FILENAME
FOREST_FIRES_PROCESSED_FILE_X = PROCESSED_DIR + "X_" + FOREST_FIRES_FILENAME
FOREST_FIRES_PROCESSED_FILE_y = PROCESSED_DIR + "y_" + FOREST_FIRES_FILENAME
